trunk/src/ATS/Aries.Portal/Controllers/DispatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.VisualBasic;
using Aries.Model.Entities;
using Aries.Model.Repositories;
using Aries.Model;
using MedTrans;
using System.IO;
using Newtonsoft.Json;
using log4net;

namespace Aries.Portal.Controllers
{
    public class DispatchController : Controller
    {
        private static readonly ILog log = LogManager.GetLogger(typeof(DispatchController));
        public class GeocodedWaypoint
        {
            public string geocoder_status { get; set; }
            public string place_id { get; set; }
            public List<string> types { get; set; }
        }

        public class Northeast
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }

        public class Southwest
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }

        public class Bounds
        {
            public Northeast northeast { get; set; }
            public Southwest southwest { get; set; }
        }

        public class Distance
        {
            public string text { get; set; }
            public int value { get; set; }
        }

        public class Duration
        {
            public string text { get; set; }
            public int value { get; set; }
        }

        public class EndLocation
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }

        public class StartLocation
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }

        public class Distance2
        {
            public string text { get; set; }
            public int value { get; set; }
        }

        public class Duration2
        {
            public string text { get; set; }
            public int value { get; set; }
        }

        public class EndLocation2
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }

        public class Polyline
        {
            public string points { get; set; }
        }

        public class StartLocation2
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }
        public class Step
        {
            public Distance2 distance { get; set; }
            public Duration2 duration { get; set; }
            public EndLocation2 end_location { get; set; }
            public string html_instructions { get; set; }
            public Polyline polyline { get; set; }
            public StartLocation2 start_location { get; set; }
            public string travel_mode { get; set; }
            public string maneuver { get; set; }
        }

        public class Location
        {
            public double lat { get; set; }
            public double lng { get; set; }
        }

        public class ViaWaypoint
        {
            public Location location { get; set; }
            public int step_index { get; set; }
            public double step_interpolation { get; set; }
        }
        public class Leg
        {
            public Distance distance { get; set; }
            public Duration duration { get; set; }
            public string end_address { get; set; }
            public EndLocation end_location { get; set; }
            public string start_address { get; set; }
            public StartLocation start_location { get; set; }
            public List<Step> steps { get; set; }
            public List<object> traffic_speed_entry { get; set; }
            public List<ViaWaypoint> via_waypoint { get; set; }
        }

        public class OverviewPolyline
        {
            public string points { get; set; }
        }

        public class Routes
        {
            public Bounds bounds { get; set; }
            public string copyrights { get; set; }
            public List<Leg> legs { get; set; }
            public OverviewPolyline overview_polyline { get; set; }
            public string summary { get; set; }
            public List<object> warnings { get; set; }
            public List<object> waypoint_order { get; set; }
        }

        public class RootObject
        {
            public List<GeocodedWaypoint> geocoded_waypoints { get; set; }
            public List<Routes> routes { get; set; }
            public string status { get; set; }
        }
        public DispatchController()
        {
            ViewBag.UserName = (new EmployeeRepository()).GetEmployeeName(System.Web.HttpContext.Current.User.Identity.Name);
        }
        string AUTO_REFRESH_RATE = "10"; // Auto Refresh Rate in Seconds
        //
        // GET: /Dispatch/
        public ActionResult Status()
        {
            return View();
        }

        public ActionResult Overview()
        {
            return View();

        }
        public JsonResult GetTrips(string fr = "", string to = "")
        {
            // TODO: 
            // May need to add filter to just get all dispatch for the day only    
            DateTime frDate = DateTime.Now.Date;
            DateTime toDate = DateTime.Now.Date;

            if (fr != "")
            {
                DateTime.TryParse(fr, out frDate);
            }
            if (to != "")
            {
                DateTime.TryParse(to, out toDate);
            }
            var dispatchList = (new DispatchRepository()).GetOpenDispatchSummary(frDate, new DateTime(toDate.Year, toDate.Month, toDate.Day, 23, 59, 59));
            //ViewData["Dispatches"] = dispatchList;
            //Response.AddHeader("Refresh", AUTO_REFRESH_RATE);
            //return View("~/Views/Dispatch/Overview.cshtml");
            JsonResult lst = Json(dispatchList, JsonRequestBehavior.AllowGet);
            return lst;

        }

        public ActionResult Alerts()
        {
            // TODO: 
            // May need to add filter to just get all dispatch for the day only     
            DateTime frDate = DateTime.Now.Date;
            DateTime toDate = new DateTime(frDate.Year, frDate.Month, frDate.Day, 23, 59, 59);
            List<DispatchSummaryView> dispatchList = (new DispatchRepository()).GetDispatchSummary(frDate, toDate);
            List<DispatchAlertView> alertList = new List<DispatchAlertView>();
            StatusListRepository sl = new StatusListRepository();

            foreach (DispatchSummaryView d in dispatchList)
            {
                if ((d.Status == "Dispatched") || (d.Status == "Open"))
                {
                    long minutes = DateAndTime.DateDiff("n", d.StatusTimestamp, DateTime.Now);

                    if (minutes >= 15)
                    {
                        alertList.Add(new DispatchAlertView
                        {
                            Id = d.Id,
                            OrderNumber = d.OrderNumber,
                            Timestamp = d.StatusTimestamp,
                            Customer = d.Customer,
                            Driver = d.Driver,
                            Status = d.Status,
                            Minutes = minutes,
                            BGcss = (minutes >= 30) ? "red" : "yellow"
                        });
                    }
                }
            }

            //var l1 = alertList.OrderByDescending(a => a.Timestamp).ToList();
            //var l2 = alertList.OrderByDescending(a => a.Minutes).ToList();

            ViewData["Alerts"] = alertList.OrderByDescending(a => a.Minutes).ToList();
            Response.AddHeader("Refresh", AUTO_REFRESH_RATE);
            //return View("~/Views/Dispatch/Alerts.cshtml");
            return View();
        }
        public ActionResult Archives()
        {
            //Session["fromDate"] = DateTime.Now.Date.ToString();
            //Session["toDate"] = DateTime.Now.Date.ToString();
            return View();

        }
        public JsonResult GetArchives(string fr = "", string to = "")
        {
            // TODO: 
            // May need to add filter to just get all dispatch for the day only    
            DateTime frDate = DateTime.Now.Date;
            DateTime toDate = DateTime.Now.Date;
            log.Info("in GetArchives");

            if (fr != "")
            {
                DateTime.TryParse(fr, out frDate);
            }
            else
            {
                if (Session["fromDate"] != null && Session["fromDate"].ToString() != "")
                {
                    fr = Session["fromDate"].ToString();
                    DateTime.TryParse(fr, out frDate);
                }
            }
            if (to != "")
            {
                DateTime.TryParse(to, out toDate);
            }
            else
            {
                if (Session["toDate"] != null && Session["toDate"].ToString() != "")
                {
                    to = Session["toDate"].ToString();
                    DateTime.TryParse(to, out toDate);
                }
            }

            Session["fromDate"] = fr;
            Session["toDate"] = to;
            var dispatchList = (new DispatchRepository()).GetDispatchSummary(frDate, new DateTime(toDate.Year, toDate.Month, toDate.Day, 23, 59, 59));
            //ViewData["Dispatches"] = dispatchList;
            JsonResult lst = Json(dispatchList, JsonRequestBehavior.AllowGet);
            return lst;
        }
        //public JsonResult GetRoutes(string fr = "", string to = "")
        //{
        //    // TODO: 
        //    // May need to add filter to just get all dispatch for the day only    
        //    DateTime frDate = DateTime.Now.Date;
        //    DateTime toDate = DateTime.Now.Date;
        //    log.Info("in GetRoutes");

        //    if (fr != "")
        //    {
        //        DateTime.TryParse(fr, out frDate);
        //    }
        //    else
        //    {

trunk/src/ATS/Aries.Portal/Views/Dispatch/Archives.cshtml
@using Aries.Model.Entities
@model Aries.Model.Entities.DispatchSummaryView
@{
   ViewBag.Title = "Dispatch Archives";
}
@section Header{
    @Styles.Render("~/Content/dataTablesCss")
}
<form  id="f" method="post" action="@Url.Action("Archives", "Dispatch")">

    <h3> Dispatch Archives</h3>
   
    <table class="table"  id="dispatchTable">
        <thead>
            <tr class="header">
                <th>Order No</th>
                <th>Time</th>
                <th>Customer</th>                      
                <th>Driver</th>                      
                <th>Status</th>                      
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Order No</th>
                <th>Time</th>
                <th>Customer</th>
                <th>Driver</th>
                <th>Status</th>
            </tr>
        </tfoot>
        <tbody>
        </tbody>
    </table>        

    <div>
        <table height="50">
            <tr>
                <td style="text-align:left">
                </td>
                <td style="text-align:left">
                </td>
                <td style="text-align:left">
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td style="text-align:left">
                    <label for="frDate">From:</label> @Html.TextBox("fr")
                </td>
                <td style="text-align:left">
                    <label for="toDate">To:</label> @Html.TextBox("to")
                </td>
                <td>
                    <input type="button" id="searchArchives" value="Search" />
                </td>
            </tr>
        </table>
    </div>
</form>
@section Scripts {
    @Scripts.Render("~/Scripts/jquery.dataTables.js");
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js");
    @Scripts.Render("~/Scripts/jquery.dataTables.columnFilter.js");

<script>
    orderSearch = ""
    customerSearch = ""
    driverSearch = ""
    statusSearch = ""

    $(document).ready(function () {
        window.applicationBaseUri = @Html.Raw(HttpUtility.JavaScriptStringEncode(Url.Content("~/"), true));
        // DataTable
                    
            $('#dispatchTable tfoot th').each(function () {
                var title = $(this).text();
                console.log('Title= ', title.toString());
                $(this).html('<input type="text" placeholder="Search ' + title + '" + "id=' + title + '" />');

                if (sessionStorage.getItem("orderSearch") !== undefined && sessionStorage.getItem("orderSearch") !== null){
                    if (title == 'Order No'){
                        $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("orderSearch") + '" + "id=' + title + '" />');
                    }
                }
                
                if (sessionStorage.getItem("customerSearch") !== undefined && sessionStorage.getItem("customerSearch") !== null){
                    if (title == 'Customer'){
                        $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("customerSearch") + '" + "id=' + title + '" />');
                    }
                }
                
                if (sessionStorage.getItem("driverSearch") !== undefined && sessionStorage.getItem("driverSearch") !== null){
                    if (title == 'Driver'){
                        $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("driverSearch") + '" + "id=' + title + '" />');
                    }
                }
                
                if (sessionStorage.getItem("statusSearch") !== undefined && sessionStorage.getItem("statusSearch") !== null){
                    if (title == 'Status'){
                        $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("statusSearch") + '" + "id=' + title + '" />');
                    }
                }
            });          

            var fr =  "";
            var frdate = "";

            if ($("#fr").text() != "") {
                fr = $("#fr").datepicker({ dateFormat: 'mm/dd/yyyy' });          
                frdate = ($.datepicker.formatDate("mm-dd-yyyy", fr));
            }
            var to =  "";
            var todate = "";

            if ($("#to").text() != "") {
                fr = $("#to").datepicker({ dateFormat: 'mm/dd/yyyy' });          
                frdate = ($.datepicker.formatDate("mm-dd-yyyy", to));
            }
            var link = window.applicationBaseUri + "Dispatch/GetArchives/";
            var table = $('#dispatchTable').DataTable({
                
                ajax: {
                    url: link,
                    data:function ( d ){
                        d.fr = $('#fr').datepicker().val(),
                        d.to = $('#to').datepicker().val()
                    },
                    dataSrc: ""
                },
                stateSave:true,
                processing: true,
                rowId: "Trip",
                initComplete:
                    function (settings) {
                        /* Apply the tooltips */
                        $('[data-toggle="tooltip"]').tooltip(
                        {
                            "container": 'body'
                        })
                    },
                columns: [

                   { 
                       data: "OrderNumber",
                       render: function (data, type, row, meta) {
                           var url = window.applicationBaseUri + 'Dispatch/Detail/' + data;
                       
                           return '<a href="' + url + '">' + data + '</a>';
                       }

                   },
                   
                   {
                       data: "Timestamp",

                       render: function (data, type, row, meta) {
                           var rowvalue = row["Timestamp"];

                           var date = new Date(parseInt(data.substr(6)));

                           var mth = date.getMonth() + 1;
                           var day = date.getDate();
                           var hh = date.getHours();
                           var ampm = (hh >= 12) ? "PM" : "AM";
                           hh = (hh <= 12) ? hh : hh-12;
                           var mm = date.getMinutes();
                           var ss = date.getSeconds();

                           var month = (mth < 10) ? "0" + mth : mth;
                           var days = (day < 10) ? "0" + day : day;
                           var hrs = (hh < 10) ? "0" + hh : hh;
                           var min = (mm < 10) ? "0" + mm : mm;
                           var sec = (ss < 10) ? "0" + ss : ss;

                           return month + "/" + days + "/" + date.getFullYear() + " "
                                  + hrs + ":" + min + ":" + sec + " " + ampm;
                       }
                   },
                   
                   { data: "Customer" },
                   { data: "Driver" },
                   { data: "Status" },

                   
                ],
                order: [[1, "asc"]],
                
            });
            table.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change', function () {
                    //tableValues[that[0][0]] = this.value;  
                    if (that[0][0] == 0) orderSearch = this.value;
                    sessionStorage.setItem("orderSearch", orderSearch);

                    if (that[0][0] == 2) customerSearch = this.value;
                    sessionStorage.setItem("customerSearch", customerSearch);

                    if (that[0][0] == 3) driverSearch = this.value;
                    sessionStorage.setItem("driverSearch", driverSearch);

                    if (that[0][0] == 4) statusSearch = this.value;
                    sessionStorage.setItem("statusSearch", statusSearch);

                    if (this.value !== null && this.value !== undefined && this.value !== ""){                
                        if (that.search() !== this.value) {
                            that
                                .search(this.value)
                                .draw();                                                
                        }
                    }

                });
            });

            table.columns().every(function () {
                var that = this;

                if (that[0][0] == 0) this.value = sessionStorage.getItem("orderSearch");                
                if (that[0][0] == 2) this.value = sessionStorage.getItem("customerSearch");                
                if (that[0][0] == 3) this.value = sessionStorage.getItem("driverSearch");                
                if (that[0][0] == 4) this.value = sessionStorage.getItem("statusSearch");   

                if (this.value !== null && this.value !== undefined && this.value !== ""){
                    that
                        .search(this.value)
                }
            });

            //setInterval(function () {
            //    console.log('Timer set');
            //    table.ajax.reload(null, false); // user paging is not reset on reload

            //}, 30000)
        //$('#fr').datepicker()
            
        //    .on("change", function (e) {
        //        table.ajax.reload(null, false); 
        //    });
        //$('#to').datepicker()
        //    .on("change", function (e) {
        //        table.ajax.reload(null, false);
        //    }); 
            $('#searchArchives').on("click", function(){
                table.ajax.reload(null, false);
            });
    });
</script>
@Scripts.Render("~/bundles/dataTablesScripts")
}

trunk/src/ATS/Aries.Portal/Views/Dispatch/Route.cshtml
@using Aries.Model.Entities
@model Aries.Model.Entities.RouteView
@{
   ViewBag.Title = "Routes";
}
@section Header{
    @Styles.Render("~/Content/dataTablesCss")
}
<form  id="f" method="post" action="@Url.Action("Routes", "Dispatch")">

    <h3>Routes</h3>
    <div class="col-md-offset-5 col-md-2">
        <input type="button" class="btn btn-default" id="btnExport" value="Export"/>
    </div>

    <table class="table"  id="dispatchTable">
        <thead>
            <tr class="header">
                <th>Time of Route</th>
                <th>Name</th>
                <th>Driver Name</th>                  
                <th>Duration</th>    
                <th>Distance</th> 
                <th>Revenue</th>  
                <th>Status</th>                      
            </tr>
        </thead>
        <tfoot>
            @*<tr>
                <th>Name</th>
                <th>Driver Name</th>
                <th>Duration</th>
                <th>Distance</th>
                <th>Revenue</th>        
            </tr>*@
        </tfoot>
        <tbody>
        
        </tbody>
    </table>        

    <div>
        <table height="50">
            <tr>
                <td style="text-align:left">
                </td>
                <td style="text-align:left">
                </td>
                <td style="text-align:left">
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td style="text-align:left">
                    <label for="frDate">From:</label> @Html.TextBox("fr")
                </td>
                <td style="text-align:left">
                    <label for="toDate">To:</label> @Html.TextBox("to")
                </td>
                <td>
                    <input type="button" id="searchArchives" value="Search" />
                </td>
                <td>
                    <input type="button" id="clearRoutes" value="Delete Routes" />
                </td>
            </tr>
        </table>
    </div>
</form>
@section Scripts {
    @Scripts.Render("~/Scripts/jquery.dataTables.js");
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js");
    @Scripts.Render("~/Scripts/jquery.dataTables.columnFilter.js");

<script>
    orderSearch = ""
    customerSearch = ""
    driverSearch = ""
    statusSearch = ""

    $(document).ready(function () {
        window.applicationBaseUri = @Html.Raw(HttpUtility.JavaScriptStringEncode(Url.Content("~/"), true));
        // DataTable
                    
            //$('#dispatchTable tfoot th').each(function () {
            //    var title = $(this).text();
            //    console.log('Title= ', title.toString());
            //    $(this).html('<input type="text" placeholder="Search ' + title + '" + "id=' + title + '" />');

            //    if (sessionStorage.getItem("orderSearch") !== undefined && sessionStorage.getItem("orderSearch") !== null){
            //        if (title == 'Order No'){
            //            $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("orderSearch") + '" + "id=' + title + '" />');
            //        }
            //    }
                
            //    if (sessionStorage.getItem("customerSearch") !== undefined && sessionStorage.getItem("customerSearch") !== null){
            //        if (title == 'Customer'){
            //            $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("customerSearch") + '" + "id=' + title + '" />');
            //        }
            //    }
                
            //    if (sessionStorage.getItem("driverSearch") !== undefined && sessionStorage.getItem("driverSearch") !== null){
            //        if (title == 'Driver'){
            //            $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("driverSearch") + '" + "id=' + title + '" />');
            //        }
            //    }
                
            //    if (sessionStorage.getItem("statusSearch") !== undefined && sessionStorage.getItem("statusSearch") !== null){
            //        if (title == 'Status'){
            //            $(this).html('<input type="text" placeholder=" ' + sessionStorage.getItem("statusSearch") + '" + "id=' + title + '" />');
            //        }
            //    }
            //});          

            var fr =  "";
            var frdate = "";

            if ($("#fr").text() != "") {
                fr = $("#fr").datepicker({ dateFormat: 'mm/dd/yyyy' });          
                frdate = ($.datepicker.formatDate("mm-dd-yyyy", fr));
            }
            var to =  "";
            var todate = "";

            if ($("#to").text() != "") {
                fr = $("#to").datepicker({ dateFormat: 'mm/dd/yyyy' });          
                frdate = ($.datepicker.formatDate("mm-dd-yyyy", to));
            }
            var link = window.applicationBaseUri + "Dispatch/GetRouteSummary/";
            var table = $('#dispatchTable').DataTable({
                
                ajax: {
                    url: link,
                    data:function ( d ){
                        d.frDate = $('#fr').datepicker().val(),
                        d.toDate = $('#to').datepicker().val()
                    },
                    dataSrc: ""
                },
                stateSave:true,
                processing: true,
                rowId: "Trip",
                initComplete:
                    function (settings) {
                        /* Apply the tooltips */
                        $('[data-toggle="tooltip"]').tooltip(
                        {
                            "container": 'body'
                        })
                    },
                columns: [

                   { data: "Timestamp"},                  
                   { data: "Name"},                  
                   { data: "DriverName"},                   
                   { data: "Duration" },
                   { data: "Distance" },
                   { data: "Revenue" },   
                   { data: "Status" },                  
                ],
                order: [[1, "asc"]],
                
            });
            //table.columns().every(function () {
            //    var that = this;

            //    $('input', this.footer()).on('keyup change', function () {
            //        //tableValues[that[0][0]] = this.value;  
            //        if (that[0][0] == 0) orderSearch = this.value;
            //        sessionStorage.setItem("orderSearch", orderSearch);

            //        if (that[0][0] == 2) customerSearch = this.value;
            //        sessionStorage.setItem("customerSearch", customerSearch);

            //        if (that[0][0] == 3) driverSearch = this.value;
            //        sessionStorage.setItem("driverSearch", driverSearch);

            //        if (that[0][0] == 4) statusSearch = this.value;
            //        sessionStorage.setItem("statusSearch", statusSearch);

            //        if (this.value !== null && this.value !== undefined && this.value !== ""){                
            //            if (that.search() !== this.value) {
            //                that
            //                    .search(this.value)
            //                    .draw();                                                
            //            }
            //        }

            //    });
            //});

            table.columns().every(function () {
                var that = this;

                if (that[0][0] == 0) this.value = sessionStorage.getItem("orderSearch");                
                if (that[0][0] == 2) this.value = sessionStorage.getItem("customerSearch");                
                if (that[0][0] == 3) this.value = sessionStorage.getItem("driverSearch");                
                if (that[0][0] == 4) this.value = sessionStorage.getItem("statusSearch");   

                if (this.value !== null && this.value !== undefined && this.value !== ""){
                    that
                        .search(this.value)
                }
            });

            //setInterval(function () {
            //    console.log('Timer set');
            //    table.ajax.reload(null, false); // user paging is not reset on reload

            //}, 30000)
        //$('#fr').datepicker()
            
        //    .on("change", function (e) {
        //        table.ajax.reload(null, false); 
        //    });
        //$('#to').datepicker()
        //    .on("change", function (e) {
        //        table.ajax.reload(null, false);
        //    }); 
        $('#searchArchives').on("click", function(){
            table.ajax.reload(null, false);
        });
        $('#btnExport').on("click", function(){
            $.ajax({
                type: "POST",
                url: window.applicationBaseUri + "Dispatch/ExportRoutes/?frDate=" + $('#fr').datepicker().val() + "&toDate=" + $('#to').datepicker().val(),
                //data:function ( d ){
                //    d.frDate = $('#fr').datepicker().val(),
                //    d.toDate = $('#to').datepicker().val()
                //},
                dataSrc: "",
                success: function (data) {
                },
                error: function (error) {
                }

            });            
        });

        $('#clearRoutes').on("click", function(){
            $.ajax({
                type: "POST",
                url: window.applicationBaseUri + "Dispatch/DeleteRoutes/",
                //data:function ( d ){
                //    d.frDate = $('#fr').datepicker().val(),
                //    d.toDate = $('#to').datepicker().val()
                //},
                dataSrc: "",
                success: function (data) {
                },
                error: function (error) {
                }

            });            
        });
    });


</script>
@Scripts.Render("~/bundles/dataTablesScripts")
}

trunk/src/ATS/Aries.Portal/Views/Dispatch/Status.cshtml
@{
  ViewBag.Title = "My Timesheet";
}

<div class="page-header">
  <h3>Driver Availability</h3>
</div>