trunk/src/ATS/Aries.Portal/Controllers/LocationController.cs
using System;
using System.IO;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using DayPilot;
using DayPilot.Web;
using DayPilot.Web.Mvc;
using DayPilot.Web.Mvc.Data;
using DayPilot.Web.Mvc.Enums;
using DayPilot.Web.Mvc.Events.Calendar;
using DayPilot.Web.Mvc.Json;

using Aries.Portal.Models;
using Aries.Model;
using Aries.Model.Entities;
using Aries.Model.Repositories;
using Aries.Utility;

using log4net;
using System.Configuration;
using System.Net.Http;
using System.Threading.Tasks;

using OfficeOpenXml;
using PdfSharp.Pdf;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace Aries.Portal.Controllers
{
    public class LocationController : Controller
    {
        #region Some Propeties
    
        private static readonly ILog log = LogManager.GetLogger(typeof(TimesheetController));
        
        int BusinessHourStart
        {
            get
            {
                int iValue = 0;
                string sValue = System.Configuration.ConfigurationManager.AppSettings["BusinessHourStart"].ToString();
                if (int.TryParse(sValue, out iValue) == false)
                {
                    iValue = 7;
                }
                return iValue;
            }
        }

        /// <summary>
        /// Get Business end time from configuration setting. Default to 18 (6 PM)
        /// </summary>
        int BusinessHourEnd
        {
            get
            {
                int iValue = 0;
                string sValue = System.Configuration.ConfigurationManager.AppSettings["BusinessHourEnd"].ToString();
                if (int.TryParse(sValue, out iValue) == false)
                {
                    iValue = 18;
                }
                return iValue;
            }
        }
        bool EmployeeApprovedFirst
        {
            get
            {
                return false;
            }
        }

        bool OfficeApprovedFirst
        {
            get
            {
                return true;
            }
        }
        #endregion


        /// <summary>
        /// Class Constructor
        /// </summary>
        public LocationController()
        {
            ViewBag.UserName = (new EmployeeRepository()).GetEmployeeName(System.Web.HttpContext.Current.User.Identity.Name);
        }

        /// <summary>
        /// Return default page when driver signs in. 
        /// </summary>
        /// <param name="Id">Employee ID</param>
        /// <returns></returns>
        public ActionResult Index(int Id = 0, string date = "")
        {
            return View();
        }

        /// <summary>
        /// Summary for all location alerts
        /// </summary>
        /// <param name="date"></param>
        /// <returns></returns>
        public ActionResult Summary(string date = "")
        {
            DateTime theDate = new DateTime();
            DateTime.TryParse(date, out theDate);
            if (theDate == new DateTime())
            {
                theDate = DateTime.Today.Date;
            }

            ViewBag.StartDate = (new Misc()).FirstDayOfWeek(theDate, DayOfWeek.Monday);
            ViewData["LocationAlertSummary"] = (new LocationRepository()).GetLocationAlertSummary(theDate);
            return View();
        }
         public void Add(string username) {
            Employee emp = (new EmployeeRepository()).GetByName(username);
            log.Info("Logging Location for " + username);
            (new LocationRepository()).Add(emp.Id);
         }
        
    }
}

trunk/src/ATS/Aries.Portal/Controllers/TimesheetController.cs
using System;
using System.IO;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using DayPilot;
using DayPilot.Web;
using DayPilot.Web.Mvc;
using DayPilot.Web.Mvc.Data;
using DayPilot.Web.Mvc.Enums;
using DayPilot.Web.Mvc.Events.Calendar;
using DayPilot.Web.Mvc.Json;

using Aries.Portal.Models;
using Aries.Model;
using Aries.Model.Entities;
using Aries.Model.Repositories;
using Aries.Utility;

using log4net;
using System.Configuration;
using System.Net.Http;
using System.Threading.Tasks;

using OfficeOpenXml;
using PdfSharp.Pdf;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace Aries.Portal.Controllers
{
    public class TimesheetController : Controller
    {
        #region Some Propeties

        private const int headerLength = 2;
        private const int dailyLogHeaderLength = 6;
        private static readonly ILog log = LogManager.GetLogger(typeof(TimesheetController));
        public enum EarnCodes
        {
            RegHours = 0, // actual code "2"
            OTHours = 1, // actual code "3"
            VacHours = 2, // actual code "5"
            BereavementHours = 3, // actual code "9"
            HolidayHours = 4 // actual code "4"
        }
        /// <summary>
        /// Get Business start time from configuration setting. Default to 7
        /// </summary>
        string timeSheetLocation = ConfigurationManager.AppSettings["ExportedTimesheetsLocation"].ToString();
        string driverLogLocation = ConfigurationManager.AppSettings["ExportedDriversLogLocation"].ToString();

        int BusinessHourStart
        {
            get
            {
                int iValue = 0;
                string sValue = System.Configuration.ConfigurationManager.AppSettings["BusinessHourStart"].ToString();
                if (int.TryParse(sValue, out iValue) == false)
                {
                    iValue = 7;
                }
                return iValue;
            }
        }

        /// <summary>
        /// Get Business end time from configuration setting. Default to 18 (6 PM)
        /// </summary>
        int BusinessHourEnd
        {
            get
            {
                int iValue = 0;
                string sValue = System.Configuration.ConfigurationManager.AppSettings["BusinessHourEnd"].ToString();
                if (int.TryParse(sValue, out iValue) == false)
                {
                    iValue = 18;
                }
                return iValue;
            }
        }
        bool EmployeeApprovedFirst
        {
            get
            {
                return false;
            }
        }

        bool OfficeApprovedFirst
        {
            get
            {
                return true;
            }
        }
        #endregion


        /// <summary>
        /// Class Constructor
        /// </summary>
        public TimesheetController()
        {
            ViewBag.UserName = (new EmployeeRepository()).GetEmployeeName(System.Web.HttpContext.Current.User.Identity.Name);
        }

        /// <summary>
        /// Return default page when driver signs in. 
        /// </summary>
        /// <param name="Id">Employee ID</param>
        /// <returns></returns>
        public ActionResult Index(int Id = 0, string date = "")
        {
            // Parsing/Collecting info 
            int userId = (Id > 0) ? Id : (new EmployeeRepository()).GetByName(HttpContext.User.Identity.Name).Id;
            DateTime theDate = (date == "") ? DateTime.Today : DateTime.Parse(date);
            DateTime thisMonday = (new Misc()).FirstDayOfWeek(DateTime.Today, DayOfWeek.Monday);
            DateTime thisSunday = thisMonday.AddDays(6);
            bool bCurrentWeek = ((theDate.Date >= thisMonday.Date) && (theDate.Date <= thisSunday.Date));
            bool bOfficeApproved = (new Helpers.Misc()).OfficeApproved(userId, thisMonday, thisSunday);
            bool bEmployeeApproved = (new Helpers.Misc()).EmployeeApproved(userId, thisMonday, thisSunday);
            bool bSignedIn = false;     // Assume it is not current work week
            bool bSignedOut = false;    // Assume it is not current work week
            bool bAdmin = (new Helpers.Misc()).IsAdmin();
            bool bManager = (new Helpers.Misc()).IsManager();
            bool bDispatch = (new Helpers.Misc()).IsDispatch();

            DateTime selectMonday = (new Misc()).FirstDayOfWeek(theDate, DayOfWeek.Monday);
            DateTime selectSunday = selectMonday.AddDays(6);


            ViewBag.UserID = userId;
            ViewBag.BusinessHourStart = BusinessHourStart;
            ViewBag.BusinessHourEnd = BusinessHourEnd;
            ViewBag.CurrentWeek = bCurrentWeek;
            ViewBag.WeekOf = selectMonday.ToString(@"MM\/dd\/yyyy") + " - " + selectSunday.ToString(@"MM\/dd\/yyyy");
            ViewBag.StartDate = theDate;
            ViewBag.IsDriver = (new Helpers.Misc()).IsDriver();
            ViewBag.IsAdmin = bAdmin;
            ViewBag.IsManager = bManager;
            ViewBag.IsDispatch = bDispatch;

            if (bCurrentWeek == true)
            {
                // In current work week - Check if employee has signed in yet
                bSignedIn = (new Helpers.Misc()).EmployeeSignedIn(userId);
                bSignedOut = !bSignedIn;
            }

            ViewBag.SignedIn = bSignedIn;
            ViewBag.SignedOut = bSignedOut;
            ViewBag.LunchTaken = (new Helpers.Misc()).EmployeeTookLunch(userId);
            ViewBag.OfficeApproved = bOfficeApproved;
            ViewBag.EmployeeApproved = bEmployeeApproved;

            ViewBag.OfficeApprovedText = bOfficeApproved ? "YES" : "NO";
            ViewBag.EmployeeApprovedText = bEmployeeApproved ? "YES" : "NO";

            Totals(userId, selectMonday, selectSunday);

            return View();
        }

        /// <summary>
        /// Employee clock-in timesheet
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult ClockIn(int Id, DateTime dt)
        {
            (new TimesheetRepository()).SignIn(Id, dt);
            return RedirectPermanent("~/Timesheet/Index/" + Id);
        }

        /// <summary>
        /// Employee clock-out timesheet
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        /// 

        public ActionResult ClockOut(int Id, DateTime date)
        {
            (new TimesheetRepository()).SignOut(Id, date);
            return RedirectPermanent("~/Timesheet/Index/" + Id);
        }

        /// <summary>
        /// Employee is taking 30 minutes lunch
        /// </summary>
        /// <param name="Id"></param>
        /// /// <returns></returns>
        [OutputCache(Duration = 0, VaryByParam = "*")]
        [HttpGet]        
        public ActionResult Lunch(int Id = 0)
        {
            (new TimesheetRepository()).TakeLunch(Id, 30);
            return RedirectPermanent("~/Timesheet/Index/" + Id);
        }
        public ActionResult Lunch30(int Id, DateTime date)
        {
            (new TimesheetRepository()).TakeLunch(Id, 30);
            return Redirect("~/Timesheet/Edit?Id=" + Id.ToString() + "&date=" + date.ToString(@"MM\/dd\/yyyy"));
        }
        public ActionResult Lunch60(int Id, DateTime date)
        {
            (new TimesheetRepository()).TakeLunch(Id, 60);
            return Redirect("~/Timesheet/Edit?Id=" + Id.ToString() + "&date=" + date.ToString(@"MM\/dd\/yyyy"));
        }
        public ActionResult Lunch30Summary(int Id, DateTime date)
        {
            (new TimesheetRepository()).TakeLunch(Id, 30);
            return Redirect("~/Timesheet/LunchSummary");
        }
        public ActionResult Lunch60Summary(int Id, DateTime date)
        {
            (new TimesheetRepository()).TakeLunch(Id, 60);
            return Redirect("~/Timesheet/LunchSummary");
        }

        public ActionResult UpdateLunch(int Id, DateTime startdate, DateTime enddate)
        {
            log.Error("Update Lunch");
            Timesheet timesheet = (new TimesheetRepository()).GetTimesheet(Id, DateTime.Today, false);
            if (timesheet == null)
                Redirect("~/Timesheet/LunchSummary");

            TimesheetDetail lst = (new TimesheetRepository()).FindLunch(timesheet.Id);

            if (lst == null) {
                TimesheetDetail newlst = new TimesheetDetail();
                newlst.ServiceCode = "Lunch";
                newlst.TimeIn = startdate;
                newlst.TimeOut = enddate;
                newlst.TimesheetID = timesheet.Id;

                (new TimesheetRepository()).AddDetail(newlst);
            } else {
                lst.TimeIn = startdate;
                lst.TimeOut = enddate;
                (new TimesheetRepository()).UpdateDetail(lst);
            }
            /* Get the time charged that lies within the lunch period */

            /*  */
            TimesheetDetail tdTC1 = (new TimesheetRepository()).GetEmployeeTimesheetDetails(Id)
                .Where(td => td.TimeIn < startdate && td.TimeOut < enddate && td.TimeOut > startdate && td.TimeIn.Date == DateTime.Now.Date
                       && td.ServiceCode == "Time-Charged").FirstOrDefault();

            TimesheetDetail tdTC2 = (new TimesheetRepository()).GetEmployeeTimesheetDetails(Id)
                .Where(td => td.TimeIn >= startdate && td.TimeOut <= enddate && td.TimeIn.Date == DateTime.Now.Date
                       && td.ServiceCode == "Time-Charged").FirstOrDefault();

            TimesheetDetail tdTC3 = (new TimesheetRepository()).GetEmployeeTimesheetDetails(Id)
                .Where(td => td.TimeIn > startdate && td.TimeOut > enddate && td.TimeIn.Date == DateTime.Now.Date
                       && td.ServiceCode == "Time-Charged").FirstOrDefault();

trunk/src/ATS/Aries.Portal/Views/Location/Summary.cshtml
@using Aries.Model.Entities
@{
    ViewBag.Title = "Location Alerts Summary";
    List<LocationAlertSummary> locAlerts = (List<LocationAlertSummary>)ViewData["LocationAlertSummary"]; 
}
@section Header{
    @Styles.Render("~/Content/dataTablesCss")
}


@*<input type="button" class="btn btn-default" id="btnExportDaily" value="Export Todays Log" onclick="location.href='@Url.Action("ExportAllDriverLog", "Timesheet", new {date= DateTime.Now})'" />*@

<h3>Location Summary (Week of @ViewBag.StartDate.ToShortDateString() - @ViewBag.StartDate.AddDays(6).ToShortDateString())</h3>

    @*style="border-collapse:collapse;"*@
<form id="f" method="post" action="@Url.Action("Summary", "Location")">
    <table class="table" id="userTable" border="1">
        <thead>
            <tr class="header">
                <th>Employee</th>
                <th>Mon</th>
                <th>Tue</th>
                <th>Wed</th>
                <th>Thu</th>
                <th>Fri</th>
                <th>Sat</th>
                <th>Sun</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in locAlerts)
                {
                    <tr>
                        <td>@item.EmployeeName</td>
                        <td>@item.Mon<br /></td>
                        <td>@item.Tue<br /></td>
                        <td>@item.Wed<br /></td>
                        <td>@item.Thu<br /></td>
                        <td>@item.Fri<br /></td>
                        <td>@item.Sat<br /></td>
                        <td>@item.Sun<br /></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</form>
    <div id="summaryCalendarSelector" class="form-horizontal" style="max-width: 300px;">
        <div class="form-group">
            <label class="control-label col-sm-3">Week:</label>
            <div class="col-sm-9">
                <div class="input-group date">
                    <input type="text" class="form-control" />
                    <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                </div>
            </div>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/Scripts/jquery.dataTables.js");
        @Scripts.Render("~/Scripts/jquery.dataTables.min.js");
        @Scripts.Render("~/Scripts/jquery.dataTables.columnFilter.js");

        <script>
            $('#summaryCalendarSelector .input-group.date').datepicker({ autoclose: true, weekStart: 1 }).on('changeDate', function (e) {
                var selected = moment(e.date).format('YYYY-MM-DD');

                var urlString = "/Location/Summary/?date=" + selected;
                window.location = urlString;

            });

            $("#userTable td").each(function () {
                var thisCell = $(this);
                var cellValue = thisCell.text();

                if (cellValue == "True") {
                    thisCell.css("background-color", "#FF0000");
                    thisCell.text(" ");
                } else if (cellValue == "False") {
                    thisCell.css("background-color", "#FFFFFF");
                    thisCell.text(" ");
                }
            }
         )
            $("#userTable").dataTable({
               // bJQueryUI: true,
                //sPaginationType: "full_numbers",
                processing: true,
                rowId: "Trip",
                initComplete:
                    function (settings) {
                        /* Apply the tooltips */
                        $('[data-toggle="tooltip"]').tooltip(
                        {
                            "container": 'body'
                        })
                    },
            });
        </script>
       @* @Scripts.Render("~/bundles/dataTablesScripts")*@
    }