trunk/src/ATS/Aries.Portal/Controllers/LocationController.cs
using System;
using System.IO;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using DayPilot;
using DayPilot.Web;
using DayPilot.Web.Mvc;
using DayPilot.Web.Mvc.Data;
using DayPilot.Web.Mvc.Enums;
using DayPilot.Web.Mvc.Events.Calendar;
using DayPilot.Web.Mvc.Json;

using Aries.Portal.Models;
using Aries.Model;
using Aries.Model.Entities;
using Aries.Model.Repositories;
using Aries.Utility;

using log4net;
using System.Configuration;
using System.Net.Http;
using System.Threading.Tasks;

using OfficeOpenXml;
using PdfSharp.Pdf;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace Aries.Portal.Controllers
{
    public class LocationController : Controller
    {
        #region Some Propeties
    
        private static readonly ILog log = LogManager.GetLogger(typeof(TimesheetController));
        
        int BusinessHourStart
        {
            get
            {
                int iValue = 0;
                string sValue = System.Configuration.ConfigurationManager.AppSettings["BusinessHourStart"].ToString();
                if (int.TryParse(sValue, out iValue) == false)
                {
                    iValue = 7;
                }
                return iValue;
            }
        }

        /// <summary>
        /// Get Business end time from configuration setting. Default to 18 (6 PM)
        /// </summary>
        int BusinessHourEnd
        {
            get
            {
                int iValue = 0;
                string sValue = System.Configuration.ConfigurationManager.AppSettings["BusinessHourEnd"].ToString();
                if (int.TryParse(sValue, out iValue) == false)
                {
                    iValue = 18;
                }
                return iValue;
            }
        }
        bool EmployeeApprovedFirst
        {
            get
            {
                return false;
            }
        }

        bool OfficeApprovedFirst
        {
            get
            {
                return true;
            }
        }
        #endregion


        /// <summary>
        /// Class Constructor
        /// </summary>
        public LocationController()
        {
            ViewBag.UserName = (new EmployeeRepository()).GetEmployeeName(System.Web.HttpContext.Current.User.Identity.Name);
        }

        /// <summary>
        /// Return default page when driver signs in. 
        /// </summary>
        /// <param name="Id">Employee ID</param>
        /// <returns></returns>
        public ActionResult Index(int Id = 0, string date = "")
        {
            return View();
        }

        /// <summary>
        /// Summary for all location alerts
        /// </summary>
        /// <param name="date"></param>
        /// <returns></returns>
        public ActionResult Summary(string date = "")
        {
            DateTime theDate = new DateTime();
            DateTime.TryParse(date, out theDate);
            if (theDate == new DateTime())
            {
                theDate = DateTime.Today.Date;
            }

            ViewBag.StartDate = (new Misc()).FirstDayOfWeek(theDate, DayOfWeek.Monday);
            ViewData["LocationAlertSummary"] = (new LocationRepository()).GetLocationAlertSummary(theDate);
            return View();
        }
         public void Add(string username) {
            Employee emp = (new EmployeeRepository()).GetByName(username);
            log.Info("Logging Location for " + username);
            (new LocationRepository()).Add(emp.Id);
         }
        
    }
}

trunk/src/ATS/Aries.Portal/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DayPilot.Web.Mvc;
using DayPilot.Web.Mvc.Json;

using Aries.Portal.Models;
using Aries.Model;
using Aries.Model.Entities;
using Aries.Model.Repositories;

namespace Aries.Portal.Controllers
{
    [HandleError]
    public class TestController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Address()
        {
            return View(new Address
            {
                Street = "",
                City = "",
                State = "",
                PostalCode = ""
            });
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Address(FormCollection form)
        {
            (new AddressRepository()).Add(new Address
            {
                Street = Convert.ToString(form["Street"]),
                City = Convert.ToString(form["City"]),
                State = Convert.ToString(form["State"]),
                PostalCode = Convert.ToString(form["PostalCode"])
            });
            return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }

        public ActionResult Customer()
        {
            List<Address> addresses = (new AddressRepository()).GetAll();
            List<string> lsAddress = new List<string>();
            foreach (Address addr in addresses)
            {
                lsAddress.Add(addr.Id + "-" + addr.Street + " // " + addr.City + "//" + addr.State + "//" + addr.PostalCode);
            }
            ViewData["Addresses"] = lsAddress;
            return View(new Customer
            {
                Name = "",
                PhoneNumber = "",
                AddressID = 0,
                FC8Id = 0,
                MedTransId = 0
            });
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Customer(FormCollection form)
        {
            string[] addr = Convert.ToString(form["Address"]).Split('-');
            (new CustomerRepository()).Add(new Customer
            {
                Name = Convert.ToString(form["Name"]),
                PhoneNumber = Convert.ToString(form["PhoneNumber"]),
                AddressID = Convert.ToInt32(addr[0]),
                FC8Id = Convert.ToInt32(form["FC8Id"]),
                MedTransId = Convert.ToInt32(form["MedTransId"])
            });
            return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }


        public ActionResult Vehicle()
        {
            return View(new Vehicle
            {
                LicensePlateNumber = "",
                Description = "",
                FC8Id = 0,
                MedTransId = 0
            });
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Vehicle(FormCollection form)
        {
            (new VehicleRepository()).Add(new Vehicle
            {
                LicensePlateNumber = Convert.ToString(form["LicensePlateNumber"]),
                Description = Convert.ToString(form["Description"]),
                FC8Id = Convert.ToInt32(form["FC8Id"]),
                MedTransId = Convert.ToInt32(form["MedTransId"])
            });
            return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }


        public ActionResult Driver()
        {
            List<Vehicle> vehicles = (new VehicleRepository()).GetAll();
            List<string> lsVehicles = new List<string>();
            foreach (Vehicle vel in vehicles)
            {
                lsVehicles.Add(vel.Id + "-" + vel.LicensePlateNumber + " // " + vel.Description);
            }
            ViewData["Vehicles"] = lsVehicles;
            return View(new Driver
            {
                Name = "",
                PhoneNumber = "",
                DriversLicenseNumber = "",
                VehicleID = 0,
                FC8Id = 0,
                MedTransId = 0
            });
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Driver(FormCollection form)
        {
            string[] addr = Convert.ToString(form["Vehicle"]).Split('-');
            (new DriverRepository()).Add(new Driver
            {
                Name = Convert.ToString(form["Name"]),
                PhoneNumber = Convert.ToString(form["PhoneNumber"]),
                DriversLicenseNumber = Convert.ToString(form["DriversLicenseNumber"]),
                VehicleID = Convert.ToInt32(addr[0]),
                FC8Id = Convert.ToInt32(form["FC8Id"]),
                MedTransId = Convert.ToInt32(form["MedTransId"])
            });
            return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }

        public ActionResult Payment()
        {
            return View(new Payment
            { 
                PaymentToDriver = false,
                PaymentToDriverAmount = 0,
                Paid = false
            });
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Payment(FormCollection form)
        {
            bool paid = false;
            if (Convert.ToString(form["Paid"]).Substring(0, 4).ToUpper() == "TRUE")
            {
                paid = true;
            }

            bool paidToDriver = false;
            if (Convert.ToString(form["PaymentToDriver"]).Substring(0, 4).ToUpper() == "TRUE")
            {
                paidToDriver = true;
            }
            
            (new PaymentRepository()).Add(new Payment
            {
                PaymentToDriver = paidToDriver,
                Paid = paid,
                PaymentToDriverAmount = Convert.ToDecimal(form["PaymentToDriverAmount"]),
            });
            return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }


        public ActionResult Order()
        {
            List<Driver> drivers = (new DriverRepository()).GetAll();
            List<string> lsDrivers = new List<string>();
            foreach (Driver d in drivers)
            {
                lsDrivers.Add(d.Id + "-" + d.Name);
            }
            ViewData["Drivers"] = lsDrivers;

            List<Customer> customers = (new CustomerRepository()).GetAll();
            List<string> lsCustomers = new List<string>();
            foreach (Customer  c in customers)
            {
                lsCustomers.Add(c.Id + "-" + c.Name);
            }
            ViewData["Customers"] = lsCustomers;

            List<Address> addresses = (new AddressRepository()).GetAll();
            List<string> lsAddress = new List<string>();
            foreach (Address addr in addresses)
            {
                lsAddress.Add(addr.Id + "-" + addr.Street + " // " + addr.City + "//" + addr.State + "//" + addr.PostalCode);
            }
            ViewData["Addresses"] = lsAddress;

            List<Payment> payments = (new PaymentRepository()).GetAll();
            List<string> lsPayments = new List<string>();
            foreach (Payment p in payments)
            {
                lsPayments.Add(p.Id + "-" + p.PaymentToDriverAmount.ToString());
            }
            ViewData["Payments"] = lsPayments;

            return View(new Dispatch
            {
                //Timestamp = DateTime.Now,
                //DriverID  = 0,
                //CustomerID = 0,
                //PaymentID = 0,
                //PickupTime = DateTime.Now,
                //OrderNumber  = "",
                //AddressID = 0 ,
                //Notes = "",
                //Service = "",
                //ServiceType = "",
                //DNLA = false
            });
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Order(FormCollection form)
        {
            string[] addr = Convert.ToString(form["Vehicle"]).Split('-');
            (new DriverRepository()).Add(new Driver
            {
                Name = Convert.ToString(form["Name"]),
                PhoneNumber = Convert.ToString(form["PhoneNumber"]),
                DriversLicenseNumber = Convert.ToString(form["DriversLicenseNumber"]),
                VehicleID = Convert.ToInt32(addr[0]),
                FC8Id = Convert.ToInt32(form["FC8Id"]),
                MedTransId = Convert.ToInt32(form["MedTransId"])
            });
            return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }

        public ActionResult Status()
        {
            List<Dispatch> dispatches = (new DispatchRepository()).GetAll();
            List<string> lsDispatches = new List<string>();
            foreach (Dispatch d in dispatches)
            {
                //lsDispatches.Add(d.Id + "-" + d.OrderNumber+ " // " + d.Timestamp);
            }
            ViewData["Dispatches"] = lsDispatches;
            return View(new Status
            {
                StatusListID = (int)Statuses.Open,
                Timestamp = DateTime.Now,
                DispatchID = 0
            });
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Status(FormCollection form)
        {
            string[] addr = Convert.ToString(form["Vehicle"]).Split('-');
            (new DriverRepository()).Add(new Driver
            {
                Name = Convert.ToString(form["Name"]),
                PhoneNumber = Convert.ToString(form["PhoneNumber"]),
                DriversLicenseNumber = Convert.ToString(form["DriversLicenseNumber"]),
                VehicleID = Convert.ToInt32(addr[0]),
                FC8Id = Convert.ToInt32(form["FC8Id"]),
                MedTransId = Convert.ToInt32(form["MedTransId"])
            });
            return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }

    }
}

trunk/src/ATS/Aries.Portal/Views/Shared/_Blank.cshtml
@using Helpers
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/Content/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/jquery.timepicker.css" />   
    <link rel="stylesheet" href="~/Content/bootstrap.css" >   

    <script src="~/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.js"></script>
    <script src="~/Scripts/jquery.timepicker.js"></script>
</head>
<body style="padding:10px">
@RenderBody()
</body>
</html>

trunk/src/ATS/Aries.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="@(Url.Content("~/Images/favicon.ico"))" type="image/x-icon" />

  <title>@ViewBag.Title - Aries Transportation</title>

  @Styles.Render("~/Content/SiteBootstrapBundle")
  @Styles.Render("~/Content/DataTableBundle")    
  @*@Styles.Render("~/Content/elements.css")*@  
  <link href="~/Content/bootstrap.css" rel="stylesheet" media="all">
  <script src="~/Scripts/DayPilot/daypilot-all.min.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Header", required: false)


</head>
<body>
    
  <nav class="navbar hidden-sm hidden-md hidden-xs navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand-logo brand img" href="/">
            <img alt="Aries Portal" src="~/Images/logo.png" class="navbar-logo">
        </a> 
      </div>
      <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav">
          @Html.Partial("_UserPartial")
        </ul>
        @Html.Partial("_LoginPartial")      

      </div>
    </div>
  </nav>
  <div class="outerDivBg">  
    <div class="innerDivBg"></div>  
  </div> 
  <div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
      <p>&copy; @DateTime.Now.Year - Aries Transportation</p>
    </footer>
  </div>

  @Styles.Render("~/Content/DataTableBundle")
  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/moment")
  @Scripts.Render("~/bundles/bootstrap")
  @RenderSection("scripts", required: false)
  @RenderSection("Templates", required: false)
</body>
</html>

trunk/src/ATS/Aries.Portal/Views/Shared/_UserPartial.cshtml
@if (Request.IsAuthenticated) {  
  <li class="dropdown" id="dispatch-dropdown-menu">
    @if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Dispatch"))
    { 
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dispatch <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li>@Html.ActionLink("Alerts", "Alerts", "Dispatch")</li>
      <li>@Html.ActionLink("Daily Overview", "Overview", "Dispatch")</li>
      <li role="separator" class="divider"></li>
        <li>@Html.ActionLink("Archives", "Archives", "Dispatch")</li>
        <li>@Html.ActionLink("Routes", "Route", "Dispatch")</li>
    </ul>
    }
  </li>
     
  <li class="dropdown" id="timesheet-dropdown-menu">
    @if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Dispatch"))
    { 
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Timesheets <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li>@Html.ActionLink("My Timesheet", "Index", "Timesheet")</li>
      <li>@Html.ActionLink("Summary", "Summary", "Timesheet")</li>
      <li>@Html.ActionLink("Time Off Requests", "TimeOffRequests", "Timesheet")</li>
        <li>@Html.ActionLink("Lunch Summary", "LunchSummary", "Timesheet")</li>
        <li>@Html.ActionLink("Holiday Summary", "HolidaySummary", "Timesheet")</li>
    @if (User.IsInRole("Admin"))
    {
      <li role="separator" class="divider"></li>
      }
    </ul>
    }
  </li>

  if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Dispatch")) {
  <li class="dropdown" id="manage-dropdown-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage <span class="caret"></span></a>
    <ul class="dropdown-menu">
        @if (!User.IsInRole("Dispatch")){
          <li>@Html.ActionLink("Users", "Users", "Manage")</li>    
        }      
        <li>@Html.ActionLink("Groups", "Groups", "Manage")</li>   
    </ul>
  </li>
    }

    if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Dispatch"))
    {
        <li class="dropdown" id="location-dropdown-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Location <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Location Alerts", "Summary", "Location")</li>
            </ul>
        </li>
    }
    @*if (User.IsInRole("Admin"))
    {
        <li class="dropdown" id="location-dropdown-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Search <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Search", "Index", "Search")</li>
            </ul>
        </li>
    }*@
     @*   
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Test Menu <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li>@Html.ActionLink("Test Page", "Index", "Test")</li>
    </ul>
  </li>*@
}